### ISSUE TITLE
HF_TOKEN

### ISSUE THREAD

**Issue by cdgraff** [mediainbox/workerbee#1]
Revisar si estamos tomando el token desde la ENV HF_TOKEN, ya que algunos repos de HF necesitan authenticacion

**Comment by gonzafirewall** [comment]
Estoy casi seguro que no se usa, dame uno de ejemplo que hayas usado así lo puedo probar

**Comment by cdgraff** [comment]
Hay algunos modelos como el que usamos en Diarizacion o aca con el de GOOGLE que no se pueden descargar sin Aceptar terminos y condiciones, por tal motivo solo te deja si estas logueado y aceptaste en la web.

Tendriamos que implementarlo igual como esta en el codigo de Diarizacion para poder bajar esos modelos desde HF

```

2024-04-07T21:53:06-03:00 <workerbee> Traceback (most recent call last):

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/utils/_errors.py", line 261, in hf_raise_for_status

2024-04-07T21:53:06-03:00 <workerbee>   File "requests/models.py", line 1021, in raise_for_status

2024-04-07T21:53:06-03:00 <workerbee> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/api/models/google/gemma-7b-it-GGUF

2024-04-07T21:53:06-03:00 <workerbee> 

2024-04-07T21:53:06-03:00 <workerbee> The above exception was the direct cause of the following exception:

2024-04-07T21:53:06-03:00 <workerbee> 

2024-04-07T21:53:06-03:00 <workerbee> Traceback (most recent call last):

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/hf_file_system.py", line 100, in _repo_and_revision_exist

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/utils/_validators.py", line 118, in _inner_fn

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/hf_api.py", line 1868, in repo_info

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/utils/_validators.py", line 118, in _inner_fn

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/hf_api.py", line 1678, in model_info

2024-04-07T21:53:06-03:00 <workerbee>   File "huggingface_hub/utils/_errors.py", line 277, in hf_raise_for_status

2024-04-07T21:53:06-03:00 <workerbee> huggingface_hub.utils._errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-66133fef-50f382af24d9594f0215eb48;9c7dec4e-530c-4820-8cfd-89bbb36c5b56)

2024-04-07T21:53:06-03:00 <workerbee> 

2024-04-07T21:53:06-03:00 <workerbee> Cannot access gated repo for url https://huggingface.co/api/models/google/gemma-7b-it-GGUF.

2024-04-07T21:53:06-03:00 <workerbee> Repo model google/gemma-7b-it-GGUF is gated. You must be authenticated to access it.

2024-04-07T21:53:06-03:00 <workerbee> 

2024-04-07T21:53:06-03:00 <workerbee> The above exception was the direct cause of the following exception:
```

**Comment by gonzafirewall** [comment]
Arreglado en el último commit
